### ISSUE TITLE
manta-init fail to download manta-marlin image 

### ISSUE THREAD

**Issue by namtzigla** [joyent/sdc-manta#1]
when I'm doing manta-init it always fail downloading the same image every time I attempt it  with the same message more or less:
`"Content-Length" header, 14213837688, does not match downloaded size, 3251593872`
(the difference is the downloaded size).

In order to avoid this before I ran `manta-init` I have to go and update this image and wait for the process to finish before running `manta-init`

this is the job log for the fail `manta-init`:

```
{
  "execution": "failed",
  "chain_results": [
    {
      "result": "Image origins have been imported",
      "error": "",
      "name": "origin_import_images",
      "started_at": "2015-02-06T00:29:03.581Z",
      "finished_at": "2015-02-06T00:29:35.150Z"
    },
    {
      "result": "Image bb9264e2-f134-11e3-9ec7-478da02d1a13 created",
      "error": "",
      "name": "import_image",
      "started_at": "2015-02-06T00:29:35.159Z",
      "finished_at": "2015-02-06T00:29:35.388Z"
    },
    {
      "result": "",
      "error": {
        "message": "\"Content-Length\" header, 14213837688, does not match downloaded size, 3251593872",
        "statusCode": 400,
        "body": {
          "code": "Upload",
          "message": "\"Content-Length\" header, 14213837688, does not match downloaded size, 3251593872"
        },
        "restCode": "Upload",
        "name": "UploadError"
      },
      "name": "add_image_file",
      "started_at": "2015-02-06T00:29:35.398Z",
      "finished_at": "2015-02-06T00:36:23.263Z"
    }
  ],
  "params": {
    "origins": [
      "dee73ee2-69ab-11e3-b593-a3f1f80ef403"
    ],
    "image_uuid": "bb9264e2-f134-11e3-9ec7-478da02d1a13",
    "source": "https://updates.joyent.com",
    "skip_owner_check": true,
    "task": "import-remote-image"
  },
  "image_uuid": "bb9264e2-f134-11e3-9ec7-478da02d1a13",
  "task": "import-remote-image",
  "target": "/import-remote-bb9264e2-f134-11e3-9ec7-478da02d1a13",
  "workflow": "d6c5d799-3fd8-471d-95e0-f1c8ad6e4f70",
  "exec_after": null,
  "num_attempts": 0,
  "name": "import-remote-image-7.0.5",
  "version": "7.0.5",
  "timeout": 7250,
  "workflow_uuid": "d6c5d799-3fd8-471d-95e0-f1c8ad6e4f70",
  "created_at": "2015-02-06T00:29:02.953Z",
  "onerror_results": [
    {
      "result": "",
      "error": "ReferenceError: async is not defined\n    at originDeleteImages (evalmachine.<anonymous>:7:5)\n    at retryTask (/opt/smartdc/workflow/node_modules/wf/lib/task-runner.js:277:16)\n    at Object.runTask (/opt/smartdc/workflow/node_modules/wf/lib/task-runner.js:341:13)\n    at runTask (/opt/smartdc/workflow/node_modules/wf/lib/job-runner.js:386:31)\n    at Array.0 (/opt/smartdc/workflow/node_modules/wf/lib/job-runner.js:463:24)\n    at Object.pipeline (/opt/smartdc/workflow/node_modules/vasync/lib/vasync.js:207:10)\n    at runChain (/opt/smartdc/workflow/node_modules/wf/lib/job-runner.js:467:16)\n    at onError (/opt/smartdc/workflow/node_modules/wf/lib/job-runner.js:528:28)\n    at /opt/smartdc/workflow/node_modules/wf/lib/job-runner.js:482:28\n    at next (/opt/smartdc/workflow/node_modules/vasync/lib/vasync.js:189:4)",
      "name": "origin_delete_images",
      "started_at": "2015-02-06T00:36:23.275Z",
      "finished_at": "2015-02-06T00:36:23.281Z"
    },
    {
      "result": "",
      "error": "task timeout error",
      "name": "origin_delete_images",
      "started_at": "2015-02-06T00:36:23.275Z",
      "finished_at": "2015-02-06T00:36:33.277Z"
    }
  ],
  "started": 1423182543581,
  "elapsed": 439.711,
  "uuid": "4be4a815-a908-43ec-a66e-08db9b438128"
}
```

**Comment by davepacheco** [comment]
Sorry for the trouble.  We have experienced this as well internally, and we believe it's a result of transient Manta-related issues that we haven't yet root-caused.

**Comment by pannon** [comment]
This is still an issue, basically it is impossible to set up Manta by following the deployment/ops guide.

Also image update seem to be broken too for marlin so the outlined solution above does not work, see the output below:

```

This update will make the following changes:
    download 1 image (13555 MiB):
        image bb9264e2-f134-11e3-9ec7-478da02d1a13 (manta-marlin@master/13.3.6)
    update "manta" service to image bb9264e2-f134-11e3-9ec7-478da02d1a13 (manta-marlin@master/13.3.6)

Would you like to continue? [y/N] y

Create work dir: /var/sdcadm/updates/20150626T072546Z
Downloading image bb9264e2-f134-11e3-9ec7-478da02d1a13 (manta-marlin@master/13.3.6)
Error importing image bb9264e2-f134-11e3-9ec7-478da02d1a13 (manta-marlin@master/13.3.6)
Update error: {"message":"imgapi client error: \"task timeout error\"","we_cause":{},"code":"SDCClient","exitStatus":1,"image":"bb9264e2-f134-11e3-9ec7-478da02d1a13"}
sdcadm update: error: imgapi client error: "task timeout error"

```

**Comment by abacon** [comment]
@namtzigla What's the command called to update just that image? I'm also getting this error, but this is my first exposure to illumos/sdc/manta so I'm a little in the dark.

**Comment by pannon** [comment]
Seems the steps are the following:

```
updates-imgadm get bb9264e2-f134-11e3-9ec7-478da02d1a13 > bb9264e2-f134-11e3-9ec7-478da02d1a13.manifest
updates-imgadm get-file -O bb9264e2-f134-11e3-9ec7-478da02d1a13

sdc-imgadm import -f /var/tmp/bb9264e2-f134-11e3-9ec7-478da02d1a13-file.gz -m bb9264e2-f134-11e3-9ec7-478da02d1a13.manifest
```

Source: http://www.listbox.com/member/archive/247449/2015/04/sort/subj/page/1/entry/18:43/20150408130519:63D51F04-DE11-11E4-A31E-C69488C6AECD/

**Comment by trentm** [comment]
@pannon thanks for digging that up.

@namtzigla I've created a separate download area (that supports resumeable download of the huge file) for that frequently problematic image and added instructions for working around the issue here: https://github.com/joyent/manta/blob/master/docs/manta-ops.md#workaround-for-manta-marlin-image-import-failure

Please let me know if that doesn't work for you. Sorry for the delay!
